"""Add friendship constraints

Revision ID: 61339758e4ec
Revises: 
Create Date: 2026-05-14 09:10:01.496165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61339758e4ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_achievement', ['user_id', 'title'])

    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_unique_constraint('unique_friend_request', ['requester_id', 'receiver_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_constraint('unique_friend_request', type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_achievement', type_='unique')

    # ### end Alembic commands ###
